#!/bin/node
const fs = require('fs');

function sum(a, b) {
    return a + b;
}
const file = fs.createWriteStream('./newtest');

const grep = file.write(`${sum(1, 2)}\n`);
console.log(grep);
const wc = fs.ReadStream('./newtest');

wc.pipe(process.stdout);